-- Create Tables
CREATE TABLE IF NOT EXISTS public.profiles (
  id UUID REFERENCES auth.users NOT NULL PRIMARY KEY,
  student_id TEXT UNIQUE,
  full_name TEXT,
  phone TEXT,
  role TEXT DEFAULT 'student',
  hostel_name TEXT,
  block TEXT,
  room_number TEXT,
  room_type TEXT,
  sharing_type TEXT,
  floor TEXT,
  bed_number TEXT,
  status TEXT DEFAULT 'Active',
  total_fees NUMERIC DEFAULT 50000,
  paid_amount NUMERIC DEFAULT 0,
  next_due_date DATE,
  profile_photo TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.meal_records (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id TEXT NOT NULL,
  meal_type TEXT NOT NULL,
  date DATE NOT NULL,
  timestamp TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(student_id, meal_type, date)
);

CREATE TABLE IF NOT EXISTS public.payments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id TEXT NOT NULL,
  amount NUMERIC NOT NULL,
  date DATE NOT NULL,
  mode TEXT NOT NULL,
  status TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS public.notifications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id TEXT,
  title TEXT NOT NULL,
  message TEXT NOT NULL,
  type TEXT NOT NULL,
  date DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS public.rooms (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  room_number TEXT UNIQUE NOT NULL,
  capacity INTEGER NOT NULL,
  occupancy INTEGER DEFAULT 0,
  type TEXT NOT NULL,
  floor TEXT NOT NULL,
  status TEXT DEFAULT 'Available'
);

CREATE TABLE IF NOT EXISTS public.rules (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category TEXT NOT NULL,
  content TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS public.menu (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  day TEXT UNIQUE NOT NULL,
  breakfast TEXT NOT NULL,
  lunch TEXT NOT NULL,
  snacks TEXT NOT NULL,
  dinner TEXT NOT NULL
);

-- Enable RLS
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.meal_records ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.payments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.rooms ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.rules ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.menu ENABLE ROW LEVEL SECURITY;

-- Policies
-- Admin Check Function (Bypasses RLS to avoid infinite recursion)
CREATE OR REPLACE FUNCTION public.is_admin()
RETURNS BOOLEAN AS $$
  SELECT EXISTS (
    SELECT 1 FROM public.profiles 
    WHERE id = auth.uid() AND role = 'admin'
  );
$$ LANGUAGE sql SECURITY DEFINER;

-- Profiles
DO $$ BEGIN
  CREATE POLICY "Profiles are viewable by owner and admin." ON public.profiles FOR SELECT USING (auth.uid() = id OR public.is_admin());
  CREATE POLICY "Users can insert their own profile." ON public.profiles FOR INSERT WITH CHECK (auth.uid() = id);
  CREATE POLICY "Users can update own profile." ON public.profiles FOR UPDATE USING (auth.uid() = id OR public.is_admin());
END $$;

-- Meal Records
DO $$ BEGIN
  CREATE POLICY "Meal records viewable by owner and admin." ON public.meal_records FOR SELECT USING (public.is_admin() OR EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND student_id = public.meal_records.student_id));
  CREATE POLICY "Admin can insert meal records." ON public.meal_records FOR INSERT WITH CHECK (public.is_admin());
END $$;

-- Payments
DO $$ BEGIN
  CREATE POLICY "Payments viewable by owner and admin." ON public.payments FOR SELECT USING (public.is_admin() OR EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND student_id = public.payments.student_id));
  CREATE POLICY "Admin can insert payments." ON public.payments FOR INSERT WITH CHECK (public.is_admin());
END $$;

-- Notifications
DO $$ BEGIN
  CREATE POLICY "Notifications viewable by target or all if broadcast." ON public.notifications FOR SELECT USING (student_id IS NULL OR EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND student_id = public.notifications.student_id));
END $$;

-- General Data (Selectable by all logged in users)
DO $$ BEGIN
  CREATE POLICY "Rooms viewable by authenticated." ON public.rooms FOR SELECT USING (auth.role() = 'authenticated');
  CREATE POLICY "Rules viewable by authenticated." ON public.rules FOR SELECT USING (auth.role() = 'authenticated');
  CREATE POLICY "Menu viewable by authenticated." ON public.menu FOR SELECT USING (auth.role() = 'authenticated');
END $$;
